name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Build Project
        uses: hoverkraft-tech/compose-action@v2.0.1
      - name: Run Integration tests
        run: dotnet test ./ApiTest
      - name: Run Unit tests
        run: dotnet test ./LibTest
