name: Tests
run-name: ${{ github.actor }} is running the projects tests
on: [push]
jobs:
  Build-Project:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        run: dotnet build
  Run-IntegrationTests:
    runs-on: ubuntu-latest
    environment: testing
    needs: Build-Project
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Build Project
        uses: hoverkraft-tech/compose-action@v2.0.1
      - name: Run Integration tests
        run: dotnet test --no-build ./ApiTest
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    environment: testing
    needs: Build-Project
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Run Unit tests
        run: dotnet test --no-build ./LibTest
